apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-passkey
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  passkey.pem: |
{{- .Values.hookshot.secrets.passkey | nindent 4 }}
