apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-registration
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  registration.yml: |
{{- .Values.hookshot.secrets.registration | nindent 4 }}
